version: '3'
services:
  backend_1: &backend
    build:
      context: .
      dockerfile: backend.dockerfile
    volumes:
      # Pass the local config
      - ./config.yaml:/app/config.yaml:ro
      - ./config.development.yaml:/app/config.development.yaml:ro
      - ./config.local.yaml:/app/config.local.yaml:ro
    # user: "${UID}:${GID}"
    command: ["--environment", "development", "--interface", "0.0.0.0", "--port", "3001"]
  backend_2: *backend
  backend_3: *backend
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    environment:
      MACPEPDB_BACKEND_BASE_URL: http://localhost:8080
      MACPEPDB_FRONTEND_INTERFACE: 0.0.0.0
      MACPEPDB_FRONTEND_PORT: 3000
    #user: "${UID}:${GID}"
    command: ["--environment", "development"]
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx-high-available.conf:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend_1
      - backend_2
      - backend_3
      - frontend
    links:
      - backend_1
      - backend_2
      - backend_3
      - frontend